/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.ldu;

import cn.edu.ldu.util.Translate;
import java.awt.Toolkit;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 罗中运
 */
public class ChatpageUI extends javax.swing.JFrame {
    String whochat;
    int mport;
      DatagramSocket psocket;
      String myname;
    /**
     * Creates new form Chatpage
     */
     public ChatpageUI(){
        initComponents();
        int x = (Toolkit.getDefaultToolkit().getScreenSize().width - this.getSize().width)/2;
        int y = (Toolkit.getDefaultToolkit().getScreenSize().height - this.getSize().height)/2;
        this.setLocation(x, y);  
     }
     
    public ChatpageUI(String myname,String touser,DatagramSocket psocket) {
       this();
        whochat=touser;//对方id
        this.myname=myname;
       this.psocket=psocket;
        System.out.println(psocket);
        this.setTitle(touser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaPriChatPanel = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPriSendPanel = new javax.swing.JTextArea();
        jButtonPriSend = new javax.swing.JButton();
        jButtonPriClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("1501罗中运20152203162");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("聊天窗口"));

        jTextAreaPriChatPanel.setColumns(20);
        jTextAreaPriChatPanel.setRows(5);
        jScrollPane1.setViewportView(jTextAreaPriChatPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jTextAreaPriSendPanel.setColumns(20);
        jTextAreaPriSendPanel.setRows(5);
        jTextAreaPriSendPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextAreaPriSendPanelKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaPriSendPanel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonPriSend.setBackground(new java.awt.Color(102, 102, 0));
        jButtonPriSend.setText("发送");
        jButtonPriSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPriSendActionPerformed(evt);
            }
        });

        jButtonPriClose.setBackground(new java.awt.Color(102, 102, 0));
        jButtonPriClose.setText("关闭");
        jButtonPriClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPriCloseActionPerformed(evt);
            }
        });

        jLabel1.setText("1501-罗中运-20152203162");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cn/edu/ldu/images/info.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jButtonPriClose)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPriSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPriClose)
                    .addComponent(jButtonPriSend)
                    .addComponent(jLabel1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        boolean flag=true;
    private void jButtonPriSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPriSendActionPerformed
        // TODO add your handling code here:
        if(flag){
            try {
                this.jTextAreaPriChatPanel.append(this.jTextAreaPriSendPanel.getText());
                //向服务器要对方端口
                cn.edu.ldu.util.LMessage lmsg=new cn.edu.ldu.util.LMessage();
                lmsg.setText(this.jTextAreaPriSendPanel.getText());
                //登录消息类型
                String remoteName="127.0.0.1";
                InetAddress remoteAddr=InetAddress.getByName(remoteName);
                lmsg.setType("M_USER");
                lmsg.setTargetId(whochat);//告诉服务器要找谁
                lmsg.setText(this.jTextAreaPriSendPanel.getText());
                lmsg.setToPort(psocket.getLocalPort());
                lmsg.setTargetUser(myname);//告诉对方我是谁
                byte[] data=Translate.ObjectToByte(lmsg); //消息对象序列化
                //定义登录报文
                DatagramPacket packet=new DatagramPacket(data,data.length,remoteAddr,60000);
                System.out.println();
                psocket.send(packet);


                } catch (SocketException ex) {
                Logger.getLogger(tset.class.getName()).log(Level.SEVERE, null, ex);
            }catch(Exception e){
            }
            flag=false;
        }else{
             try {
                   this.jTextAreaPriChatPanel.append(this.jTextAreaPriSendPanel.getText());
               cn.edu.ldu.util.LMessage lmsg=new cn.edu.ldu.util.LMessage();
                lmsg.setText(this.jTextAreaPriSendPanel.getText());
                //登录消息类型
                String remoteName="127.0.0.1";
                InetAddress remoteAddr=InetAddress.getByName(remoteName);
                lmsg.setType("xiaoxi");
                lmsg.setTargetId(whochat);//告诉服务器要找谁
                lmsg.setText(this.jTextAreaPriSendPanel.getText());
                lmsg.setToPort(psocket.getLocalPort());
                lmsg.setTargetUser(myname);//告诉对方我是谁
                byte[] data=Translate.ObjectToByte(lmsg); //消息对象序列化
                //定义登录报文
                DatagramPacket packet=new DatagramPacket(data,data.length,remoteAddr,60000);
                System.out.println();
                psocket.send(packet);


                } catch (SocketException ex) {
                Logger.getLogger(tset.class.getName()).log(Level.SEVERE, null, ex);
            }catch(Exception e){
                
            }
        }
        
        this.jTextAreaPriSendPanel.setText("");
    }//GEN-LAST:event_jButtonPriSendActionPerformed

    private void jButtonPriCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPriCloseActionPerformed
        // TODO add your handling code here:
        this.dispose(); 
    }//GEN-LAST:event_jButtonPriCloseActionPerformed

    private void jTextAreaPriSendPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaPriSendPanelKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            if(flag){
               try {

                   this.jTextAreaPriChatPanel.append(this.jTextAreaPriSendPanel.getText());
                   //向服务器要对方端口
                   cn.edu.ldu.util.LMessage lmsg=new cn.edu.ldu.util.LMessage();
                   lmsg.setText(this.jTextAreaPriSendPanel.getText());
                   //登录消息类型
                   String remoteName="127.0.0.1";
                   InetAddress remoteAddr=InetAddress.getByName(remoteName);
                   lmsg.setType("M_USER");
                   lmsg.setTargetId(whochat);//告诉服务器要找谁
                   lmsg.setText(this.jTextAreaPriSendPanel.getText());
                   lmsg.setToPort(psocket.getLocalPort());
                   lmsg.setTargetUser(myname);//告诉对方我是谁
                   byte[] data=Translate.ObjectToByte(lmsg); //消息对象序列化
                   //定义登录报文
                   DatagramPacket packet=new DatagramPacket(data,data.length,remoteAddr,60000);
                   System.out.println();
                   psocket.send(packet);


                   } catch (SocketException ex) {
                   Logger.getLogger(tset.class.getName()).log(Level.SEVERE, null, ex);
               }catch(Exception e){
               }
               flag=false;
           }else{
                try {
                      this.jTextAreaPriChatPanel.append(this.jTextAreaPriSendPanel.getText());
                  cn.edu.ldu.util.LMessage lmsg=new cn.edu.ldu.util.LMessage();
                   lmsg.setText(this.jTextAreaPriSendPanel.getText());
                   //登录消息类型
                   String remoteName="127.0.0.1";
                   InetAddress remoteAddr=InetAddress.getByName(remoteName);
                   lmsg.setType("xiaoxi");
                   lmsg.setTargetId(whochat);//告诉服务器要找谁
                   lmsg.setText(this.jTextAreaPriSendPanel.getText());
                   lmsg.setToPort(psocket.getLocalPort());
                   lmsg.setTargetUser(myname);//告诉对方我是谁
                   byte[] data=Translate.ObjectToByte(lmsg); //消息对象序列化
                   //定义登录报文
                   DatagramPacket packet=new DatagramPacket(data,data.length,remoteAddr,60000);
                   System.out.println();
                   psocket.send(packet);


                   } catch (SocketException ex) {
                   Logger.getLogger(tset.class.getName()).log(Level.SEVERE, null, ex);
               }catch(Exception e){

               }
           }

           this.jTextAreaPriSendPanel.setText("");
       }
    }//GEN-LAST:event_jTextAreaPriSendPanelKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatpageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatpageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatpageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatpageUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatpageUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPriClose;
    private javax.swing.JButton jButtonPriSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextAreaPriChatPanel;
    public javax.swing.JTextArea jTextAreaPriSendPanel;
    // End of variables declaration//GEN-END:variables
}
